//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.02 at 12:07:38 PM PST 
//


package org.yeastrc.emozi.emozi_import.api.xml_dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}psm_annotation_cutoffs_on_import"/>
 *         &lt;element ref="{}reported_peptide_annotation_cutoffs_on_import" minOccurs="0"/>
 *         &lt;element ref="{}matched_protein_annotation_cutoffs_on_import"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "psmAnnotationCutoffsOnImport",
    "reportedPeptideAnnotationCutoffsOnImport",
    "matchedProteinAnnotationCutoffsOnImport"
})
@XmlRootElement(name = "annotation_cutoffs_on_import")
public class AnnotationCutoffsOnImport {

    @XmlElement(name = "psm_annotation_cutoffs_on_import", required = true)
    protected PsmAnnotationCutoffsOnImport psmAnnotationCutoffsOnImport;
    @XmlElement(name = "reported_peptide_annotation_cutoffs_on_import")
    protected ReportedPeptideAnnotationCutoffsOnImport reportedPeptideAnnotationCutoffsOnImport;
    @XmlElement(name = "matched_protein_annotation_cutoffs_on_import", required = true)
    protected MatchedProteinAnnotationCutoffsOnImport matchedProteinAnnotationCutoffsOnImport;

    /**
     * Gets the value of the psmAnnotationCutoffsOnImport property.
     * 
     * @return
     *     possible object is
     *     {@link PsmAnnotationCutoffsOnImport }
     *     
     */
    public PsmAnnotationCutoffsOnImport getPsmAnnotationCutoffsOnImport() {
        return psmAnnotationCutoffsOnImport;
    }

    /**
     * Sets the value of the psmAnnotationCutoffsOnImport property.
     * 
     * @param value
     *     allowed object is
     *     {@link PsmAnnotationCutoffsOnImport }
     *     
     */
    public void setPsmAnnotationCutoffsOnImport(PsmAnnotationCutoffsOnImport value) {
        this.psmAnnotationCutoffsOnImport = value;
    }

    /**
     * Gets the value of the reportedPeptideAnnotationCutoffsOnImport property.
     * 
     * @return
     *     possible object is
     *     {@link ReportedPeptideAnnotationCutoffsOnImport }
     *     
     */
    public ReportedPeptideAnnotationCutoffsOnImport getReportedPeptideAnnotationCutoffsOnImport() {
        return reportedPeptideAnnotationCutoffsOnImport;
    }

    /**
     * Sets the value of the reportedPeptideAnnotationCutoffsOnImport property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportedPeptideAnnotationCutoffsOnImport }
     *     
     */
    public void setReportedPeptideAnnotationCutoffsOnImport(ReportedPeptideAnnotationCutoffsOnImport value) {
        this.reportedPeptideAnnotationCutoffsOnImport = value;
    }

    /**
     * Gets the value of the matchedProteinAnnotationCutoffsOnImport property.
     * 
     * @return
     *     possible object is
     *     {@link MatchedProteinAnnotationCutoffsOnImport }
     *     
     */
    public MatchedProteinAnnotationCutoffsOnImport getMatchedProteinAnnotationCutoffsOnImport() {
        return matchedProteinAnnotationCutoffsOnImport;
    }

    /**
     * Sets the value of the matchedProteinAnnotationCutoffsOnImport property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchedProteinAnnotationCutoffsOnImport }
     *     
     */
    public void setMatchedProteinAnnotationCutoffsOnImport(MatchedProteinAnnotationCutoffsOnImport value) {
        this.matchedProteinAnnotationCutoffsOnImport = value;
    }

}
