//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.21 at 04:09:34 PM PST 
//


package org.yeastrc.emozi.emozi_import.api.xml_dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}visible_psm_annotations"/>
 *         &lt;element ref="{}visible_reported_peptide_annotations" minOccurs="0"/>
 *         &lt;element ref="{}visible_matched_protein_annotations" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "visiblePsmAnnotations",
    "visibleReportedPeptideAnnotations",
    "visibleMatchedProteinAnnotations"
})
@XmlRootElement(name = "default_visible_annotations")
public class DefaultVisibleAnnotations {

    @XmlElement(name = "visible_psm_annotations", required = true)
    protected VisiblePsmAnnotations visiblePsmAnnotations;
    @XmlElement(name = "visible_reported_peptide_annotations")
    protected VisibleReportedPeptideAnnotations visibleReportedPeptideAnnotations;
    @XmlElement(name = "visible_matched_protein_annotations")
    protected VisibleMatchedProteinAnnotations visibleMatchedProteinAnnotations;

    /**
     * Gets the value of the visiblePsmAnnotations property.
     * 
     * @return
     *     possible object is
     *     {@link VisiblePsmAnnotations }
     *     
     */
    public VisiblePsmAnnotations getVisiblePsmAnnotations() {
        return visiblePsmAnnotations;
    }

    /**
     * Sets the value of the visiblePsmAnnotations property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisiblePsmAnnotations }
     *     
     */
    public void setVisiblePsmAnnotations(VisiblePsmAnnotations value) {
        this.visiblePsmAnnotations = value;
    }

    /**
     * Gets the value of the visibleReportedPeptideAnnotations property.
     * 
     * @return
     *     possible object is
     *     {@link VisibleReportedPeptideAnnotations }
     *     
     */
    public VisibleReportedPeptideAnnotations getVisibleReportedPeptideAnnotations() {
        return visibleReportedPeptideAnnotations;
    }

    /**
     * Sets the value of the visibleReportedPeptideAnnotations property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisibleReportedPeptideAnnotations }
     *     
     */
    public void setVisibleReportedPeptideAnnotations(VisibleReportedPeptideAnnotations value) {
        this.visibleReportedPeptideAnnotations = value;
    }

    /**
     * Gets the value of the visibleMatchedProteinAnnotations property.
     * 
     * @return
     *     possible object is
     *     {@link VisibleMatchedProteinAnnotations }
     *     
     */
    public VisibleMatchedProteinAnnotations getVisibleMatchedProteinAnnotations() {
        return visibleMatchedProteinAnnotations;
    }

    /**
     * Sets the value of the visibleMatchedProteinAnnotations property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisibleMatchedProteinAnnotations }
     *     
     */
    public void setVisibleMatchedProteinAnnotations(VisibleMatchedProteinAnnotations value) {
        this.visibleMatchedProteinAnnotations = value;
    }

}
