//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.12 at 02:48:17 PM PST 
//


package org.yeastrc.emozi.emozi_import.api.xml_dto;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.yeastrc.emozi.emozi_import.api.xml_dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FileContent_QNAME = new QName("", "file_content");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.yeastrc.emozi.emozi_import.api.xml_dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SearchProgram }
     * 
     */
    public SearchProgram createSearchProgram() {
        return new SearchProgram();
    }

    /**
     * Create an instance of {@link ReportedPeptide }
     * 
     */
    public ReportedPeptide createReportedPeptide() {
        return new ReportedPeptide();
    }

    /**
     * Create an instance of {@link MatchedProteinRefs }
     * 
     */
    public MatchedProteinRefs createMatchedProteinRefs() {
        return new MatchedProteinRefs();
    }

    /**
     * Create an instance of {@link Protein }
     * 
     */
    public Protein createProtein() {
        return new Protein();
    }

    /**
     * Create an instance of {@link EmoziInput }
     * 
     */
    public EmoziInput createEmoziInput() {
        return new EmoziInput();
    }

    /**
     * Create an instance of {@link SearchProgramInfo }
     * 
     */
    public SearchProgramInfo createSearchProgramInfo() {
        return new SearchProgramInfo();
    }

    /**
     * Create an instance of {@link SearchPrograms }
     * 
     */
    public SearchPrograms createSearchPrograms() {
        return new SearchPrograms();
    }

    /**
     * Create an instance of {@link SearchProgram.PsmAnnotationTypes }
     * 
     */
    public SearchProgram.PsmAnnotationTypes createSearchProgramPsmAnnotationTypes() {
        return new SearchProgram.PsmAnnotationTypes();
    }

    /**
     * Create an instance of {@link SearchProgram.ReportedPeptideAnnotationTypes }
     * 
     */
    public SearchProgram.ReportedPeptideAnnotationTypes createSearchProgramReportedPeptideAnnotationTypes() {
        return new SearchProgram.ReportedPeptideAnnotationTypes();
    }

    /**
     * Create an instance of {@link SearchProgram.MatchedProteinAnnotationTypes }
     * 
     */
    public SearchProgram.MatchedProteinAnnotationTypes createSearchProgramMatchedProteinAnnotationTypes() {
        return new SearchProgram.MatchedProteinAnnotationTypes();
    }

    /**
     * Create an instance of {@link DefaultVisibleAnnotations }
     * 
     */
    public DefaultVisibleAnnotations createDefaultVisibleAnnotations() {
        return new DefaultVisibleAnnotations();
    }

    /**
     * Create an instance of {@link VisiblePsmAnnotations }
     * 
     */
    public VisiblePsmAnnotations createVisiblePsmAnnotations() {
        return new VisiblePsmAnnotations();
    }

    /**
     * Create an instance of {@link SearchAnnotation }
     * 
     */
    public SearchAnnotation createSearchAnnotation() {
        return new SearchAnnotation();
    }

    /**
     * Create an instance of {@link VisibleReportedPeptideAnnotations }
     * 
     */
    public VisibleReportedPeptideAnnotations createVisibleReportedPeptideAnnotations() {
        return new VisibleReportedPeptideAnnotations();
    }

    /**
     * Create an instance of {@link VisibleMatchedProteinAnnotations }
     * 
     */
    public VisibleMatchedProteinAnnotations createVisibleMatchedProteinAnnotations() {
        return new VisibleMatchedProteinAnnotations();
    }

    /**
     * Create an instance of {@link AnnotationSortOrder }
     * 
     */
    public AnnotationSortOrder createAnnotationSortOrder() {
        return new AnnotationSortOrder();
    }

    /**
     * Create an instance of {@link PsmAnnotationSortOrder }
     * 
     */
    public PsmAnnotationSortOrder createPsmAnnotationSortOrder() {
        return new PsmAnnotationSortOrder();
    }

    /**
     * Create an instance of {@link ReportedPeptideAnnotationSortOrder }
     * 
     */
    public ReportedPeptideAnnotationSortOrder createReportedPeptideAnnotationSortOrder() {
        return new ReportedPeptideAnnotationSortOrder();
    }

    /**
     * Create an instance of {@link MatchedProteinAnnotationSortOrder }
     * 
     */
    public MatchedProteinAnnotationSortOrder createMatchedProteinAnnotationSortOrder() {
        return new MatchedProteinAnnotationSortOrder();
    }

    /**
     * Create an instance of {@link ReportedPeptides }
     * 
     */
    public ReportedPeptides createReportedPeptides() {
        return new ReportedPeptides();
    }

    /**
     * Create an instance of {@link Psms }
     * 
     */
    public Psms createPsms() {
        return new Psms();
    }

    /**
     * Create an instance of {@link Psm }
     * 
     */
    public Psm createPsm() {
        return new Psm();
    }

    /**
     * Create an instance of {@link FilterablePsmAnnotations }
     * 
     */
    public FilterablePsmAnnotations createFilterablePsmAnnotations() {
        return new FilterablePsmAnnotations();
    }

    /**
     * Create an instance of {@link FilterablePsmAnnotation }
     * 
     */
    public FilterablePsmAnnotation createFilterablePsmAnnotation() {
        return new FilterablePsmAnnotation();
    }

    /**
     * Create an instance of {@link DescriptivePsmAnnotations }
     * 
     */
    public DescriptivePsmAnnotations createDescriptivePsmAnnotations() {
        return new DescriptivePsmAnnotations();
    }

    /**
     * Create an instance of {@link DescriptivePsmAnnotation }
     * 
     */
    public DescriptivePsmAnnotation createDescriptivePsmAnnotation() {
        return new DescriptivePsmAnnotation();
    }

    /**
     * Create an instance of {@link ReportedPeptide.ReportedPeptideAnnotations }
     * 
     */
    public ReportedPeptide.ReportedPeptideAnnotations createReportedPeptideReportedPeptideAnnotations() {
        return new ReportedPeptide.ReportedPeptideAnnotations();
    }

    /**
     * Create an instance of {@link Modifications }
     * 
     */
    public Modifications createModifications() {
        return new Modifications();
    }

    /**
     * Create an instance of {@link Modification }
     * 
     */
    public Modification createModification() {
        return new Modification();
    }

    /**
     * Create an instance of {@link PeptideIsotopeLabels }
     * 
     */
    public PeptideIsotopeLabels createPeptideIsotopeLabels() {
        return new PeptideIsotopeLabels();
    }

    /**
     * Create an instance of {@link PeptideIsotopeLabel }
     * 
     */
    public PeptideIsotopeLabel createPeptideIsotopeLabel() {
        return new PeptideIsotopeLabel();
    }

    /**
     * Create an instance of {@link MatchedProteinRefs.MatchedProteinRef }
     * 
     */
    public MatchedProteinRefs.MatchedProteinRef createMatchedProteinRefsMatchedProteinRef() {
        return new MatchedProteinRefs.MatchedProteinRef();
    }

    /**
     * Create an instance of {@link MatchedProteins }
     * 
     */
    public MatchedProteins createMatchedProteins() {
        return new MatchedProteins();
    }

    /**
     * Create an instance of {@link ProteinLabel }
     * 
     */
    public ProteinLabel createProteinLabel() {
        return new ProteinLabel();
    }

    /**
     * Create an instance of {@link Protein.MatchedProteinAnnotations }
     * 
     */
    public Protein.MatchedProteinAnnotations createProteinMatchedProteinAnnotations() {
        return new Protein.MatchedProteinAnnotations();
    }

    /**
     * Create an instance of {@link StaticModifications }
     * 
     */
    public StaticModifications createStaticModifications() {
        return new StaticModifications();
    }

    /**
     * Create an instance of {@link StaticModification }
     * 
     */
    public StaticModification createStaticModification() {
        return new StaticModification();
    }

    /**
     * Create an instance of {@link ConfigurationFiles }
     * 
     */
    public ConfigurationFiles createConfigurationFiles() {
        return new ConfigurationFiles();
    }

    /**
     * Create an instance of {@link ConfigurationFile }
     * 
     */
    public ConfigurationFile createConfigurationFile() {
        return new ConfigurationFile();
    }

    /**
     * Create an instance of {@link DescriptiveMatchedProteinAnnotationTypes }
     * 
     */
    public DescriptiveMatchedProteinAnnotationTypes createDescriptiveMatchedProteinAnnotationTypes() {
        return new DescriptiveMatchedProteinAnnotationTypes();
    }

    /**
     * Create an instance of {@link DescriptiveMatchedProteinAnnotationType }
     * 
     */
    public DescriptiveMatchedProteinAnnotationType createDescriptiveMatchedProteinAnnotationType() {
        return new DescriptiveMatchedProteinAnnotationType();
    }

    /**
     * Create an instance of {@link FilterablePsmAnnotationTypes }
     * 
     */
    public FilterablePsmAnnotationTypes createFilterablePsmAnnotationTypes() {
        return new FilterablePsmAnnotationTypes();
    }

    /**
     * Create an instance of {@link FilterablePsmAnnotationType }
     * 
     */
    public FilterablePsmAnnotationType createFilterablePsmAnnotationType() {
        return new FilterablePsmAnnotationType();
    }

    /**
     * Create an instance of {@link DescriptiveReportedPeptideAnnotationTypes }
     * 
     */
    public DescriptiveReportedPeptideAnnotationTypes createDescriptiveReportedPeptideAnnotationTypes() {
        return new DescriptiveReportedPeptideAnnotationTypes();
    }

    /**
     * Create an instance of {@link DescriptiveReportedPeptideAnnotationType }
     * 
     */
    public DescriptiveReportedPeptideAnnotationType createDescriptiveReportedPeptideAnnotationType() {
        return new DescriptiveReportedPeptideAnnotationType();
    }

    /**
     * Create an instance of {@link FilterableMatchedProteinAnnotationType }
     * 
     */
    public FilterableMatchedProteinAnnotationType createFilterableMatchedProteinAnnotationType() {
        return new FilterableMatchedProteinAnnotationType();
    }

    /**
     * Create an instance of {@link FilterableMatchedProteinAnnotations }
     * 
     */
    public FilterableMatchedProteinAnnotations createFilterableMatchedProteinAnnotations() {
        return new FilterableMatchedProteinAnnotations();
    }

    /**
     * Create an instance of {@link FilterableMatchedProteinAnnotation }
     * 
     */
    public FilterableMatchedProteinAnnotation createFilterableMatchedProteinAnnotation() {
        return new FilterableMatchedProteinAnnotation();
    }

    /**
     * Create an instance of {@link DescriptiveReportedPeptideAnnotations }
     * 
     */
    public DescriptiveReportedPeptideAnnotations createDescriptiveReportedPeptideAnnotations() {
        return new DescriptiveReportedPeptideAnnotations();
    }

    /**
     * Create an instance of {@link DescriptiveReportedPeptideAnnotation }
     * 
     */
    public DescriptiveReportedPeptideAnnotation createDescriptiveReportedPeptideAnnotation() {
        return new DescriptiveReportedPeptideAnnotation();
    }

    /**
     * Create an instance of {@link DescriptivePsmAnnotationTypes }
     * 
     */
    public DescriptivePsmAnnotationTypes createDescriptivePsmAnnotationTypes() {
        return new DescriptivePsmAnnotationTypes();
    }

    /**
     * Create an instance of {@link DescriptivePsmAnnotationType }
     * 
     */
    public DescriptivePsmAnnotationType createDescriptivePsmAnnotationType() {
        return new DescriptivePsmAnnotationType();
    }

    /**
     * Create an instance of {@link FilterableReportedPeptideAnnotationType }
     * 
     */
    public FilterableReportedPeptideAnnotationType createFilterableReportedPeptideAnnotationType() {
        return new FilterableReportedPeptideAnnotationType();
    }

    /**
     * Create an instance of {@link FilterableReportedPeptideAnnotations }
     * 
     */
    public FilterableReportedPeptideAnnotations createFilterableReportedPeptideAnnotations() {
        return new FilterableReportedPeptideAnnotations();
    }

    /**
     * Create an instance of {@link FilterableReportedPeptideAnnotation }
     * 
     */
    public FilterableReportedPeptideAnnotation createFilterableReportedPeptideAnnotation() {
        return new FilterableReportedPeptideAnnotation();
    }

    /**
     * Create an instance of {@link FilterableReportedPeptideAnnotationTypes }
     * 
     */
    public FilterableReportedPeptideAnnotationTypes createFilterableReportedPeptideAnnotationTypes() {
        return new FilterableReportedPeptideAnnotationTypes();
    }

    /**
     * Create an instance of {@link DescriptiveMatchedProteinAnnotations }
     * 
     */
    public DescriptiveMatchedProteinAnnotations createDescriptiveMatchedProteinAnnotations() {
        return new DescriptiveMatchedProteinAnnotations();
    }

    /**
     * Create an instance of {@link DescriptiveMatchedProteinAnnotation }
     * 
     */
    public DescriptiveMatchedProteinAnnotation createDescriptiveMatchedProteinAnnotation() {
        return new DescriptiveMatchedProteinAnnotation();
    }

    /**
     * Create an instance of {@link FilterableMatchedProteinAnnotationTypes }
     * 
     */
    public FilterableMatchedProteinAnnotationTypes createFilterableMatchedProteinAnnotationTypes() {
        return new FilterableMatchedProteinAnnotationTypes();
    }

    /**
     * Create an instance of {@link SearchAnnotationCutoff }
     * 
     */
    public SearchAnnotationCutoff createSearchAnnotationCutoff() {
        return new SearchAnnotationCutoff();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "file_content")
    public JAXBElement<byte[]> createFileContent(byte[] value) {
        return new JAXBElement<byte[]>(_FileContent_QNAME, byte[].class, null, ((byte[]) value));
    }

}
