//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.21 at 10:06:54 AM PDT 
//


package org.yeastrc.limelight.limelight_import.api.xml_dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}search_comments" minOccurs="0"/>
 *         &lt;element ref="{}search_program_info"/>
 *         &lt;element ref="{}reported_peptides"/>
 *         &lt;element ref="{}matched_proteins"/>
 *         &lt;element ref="{}static_modifications" minOccurs="0"/>
 *         &lt;element ref="{}configuration_files" minOccurs="0"/>
 *         &lt;element ref="{}conversion_program" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="fasta_filename" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="data_path" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "searchComments",
    "searchProgramInfo",
    "reportedPeptides",
    "matchedProteins",
    "staticModifications",
    "configurationFiles",
    "conversionProgram"
})
@XmlRootElement(name = "limelight_input")
public class LimelightInput {

    @XmlElement(name = "search_comments")
    protected SearchComments searchComments;
    @XmlElement(name = "search_program_info", required = true)
    protected SearchProgramInfo searchProgramInfo;
    @XmlElement(name = "reported_peptides", required = true)
    protected ReportedPeptides reportedPeptides;
    @XmlElement(name = "matched_proteins", required = true)
    protected MatchedProteins matchedProteins;
    @XmlElement(name = "static_modifications")
    protected StaticModifications staticModifications;
    @XmlElement(name = "configuration_files")
    protected ConfigurationFiles configurationFiles;
    @XmlElement(name = "conversion_program")
    protected ConversionProgram conversionProgram;
    @XmlAttribute(name = "fasta_filename", required = true)
    protected String fastaFilename;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "data_path")
    @XmlSchemaType(name = "anySimpleType")
    protected String dataPath;

    /**
     * Comments to be associated with this search. Each search_comment is added to database as a separate comment.
     * 
     * @return
     *     possible object is
     *     {@link SearchComments }
     *     
     */
    public SearchComments getSearchComments() {
        return searchComments;
    }

    /**
     * Sets the value of the searchComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchComments }
     *     
     */
    public void setSearchComments(SearchComments value) {
        this.searchComments = value;
    }

    /**
     * Gets the value of the searchProgramInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SearchProgramInfo }
     *     
     */
    public SearchProgramInfo getSearchProgramInfo() {
        return searchProgramInfo;
    }

    /**
     * Sets the value of the searchProgramInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchProgramInfo }
     *     
     */
    public void setSearchProgramInfo(SearchProgramInfo value) {
        this.searchProgramInfo = value;
    }

    /**
     * All the distinct reported peptides from a PSM search. A reported peptide is a string that uniquely identifies an identified peptide IN THIS SEARCH. For example “PEPTIDE” and “PEP[43.023]TIDE” would be different reported peptides, identified by different PSMs. There is no expected syntax for reported peptides, but the reported peptide string must be unique.
     * 
     * @return
     *     possible object is
     *     {@link ReportedPeptides }
     *     
     */
    public ReportedPeptides getReportedPeptides() {
        return reportedPeptides;
    }

    /**
     * Sets the value of the reportedPeptides property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportedPeptides }
     *     
     */
    public void setReportedPeptides(ReportedPeptides value) {
        this.reportedPeptides = value;
    }

    /**
     * Contains the matched protein groups. A matched_protein is a protein matched by a peptide found in the search. A matched_protein_group contains the proteins that were matched by exactly the same group of peptides, and so are indistinguishble from one another in terms of the peptides found. 
     * 
     * @return
     *     possible object is
     *     {@link MatchedProteins }
     *     
     */
    public MatchedProteins getMatchedProteins() {
        return matchedProteins;
    }

    /**
     * Sets the value of the matchedProteins property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchedProteins }
     *     
     */
    public void setMatchedProteins(MatchedProteins value) {
        this.matchedProteins = value;
    }

    /**
     * Gets the value of the staticModifications property.
     * 
     * @return
     *     possible object is
     *     {@link StaticModifications }
     *     
     */
    public StaticModifications getStaticModifications() {
        return staticModifications;
    }

    /**
     * Sets the value of the staticModifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link StaticModifications }
     *     
     */
    public void setStaticModifications(StaticModifications value) {
        this.staticModifications = value;
    }

    /**
     * (Optional) The configuration files associated with the search.
     * 
     * @return
     *     possible object is
     *     {@link ConfigurationFiles }
     *     
     */
    public ConfigurationFiles getConfigurationFiles() {
        return configurationFiles;
    }

    /**
     * Sets the value of the configurationFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigurationFiles }
     *     
     */
    public void setConfigurationFiles(ConfigurationFiles value) {
        this.configurationFiles = value;
    }

    /**
     * Gets the value of the conversionProgram property.
     * 
     * @return
     *     possible object is
     *     {@link ConversionProgram }
     *     
     */
    public ConversionProgram getConversionProgram() {
        return conversionProgram;
    }

    /**
     * Sets the value of the conversionProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConversionProgram }
     *     
     */
    public void setConversionProgram(ConversionProgram value) {
        this.conversionProgram = value;
    }

    /**
     * Gets the value of the fastaFilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFastaFilename() {
        return fastaFilename;
    }

    /**
     * Sets the value of the fastaFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFastaFilename(String value) {
        this.fastaFilename = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the dataPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataPath() {
        return dataPath;
    }

    /**
     * Sets the value of the dataPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataPath(String value) {
        this.dataPath = value;
    }

}
