//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.07 at 12:50:09 PM PDT 
//


package org.yeastrc.limelight.limelight_import.api.xml_dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}peptide_isotope_label" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "peptideIsotopeLabel"
})
@XmlRootElement(name = "peptide_isotope_labels")
public class PeptideIsotopeLabels {

    @XmlElement(name = "peptide_isotope_label")
    protected PeptideIsotopeLabel peptideIsotopeLabel;

    /**
     * Gets the value of the peptideIsotopeLabel property.
     * 
     * @return
     *     possible object is
     *     {@link PeptideIsotopeLabel }
     *     
     */
    public PeptideIsotopeLabel getPeptideIsotopeLabel() {
        return peptideIsotopeLabel;
    }

    /**
     * Sets the value of the peptideIsotopeLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeptideIsotopeLabel }
     *     
     */
    public void setPeptideIsotopeLabel(PeptideIsotopeLabel value) {
        this.peptideIsotopeLabel = value;
    }

}
