//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.21 at 10:06:54 AM PDT 
//


package org.yeastrc.limelight.limelight_import.api.xml_dto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}psm_open_modification_position" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="mass" use="required" type="{}mass" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "psmOpenModificationPosition"
})
@XmlRootElement(name = "psm_open_modification")
public class PsmOpenModification {

    @XmlElement(name = "psm_open_modification_position")
    protected List<PsmOpenModificationPosition> psmOpenModificationPosition;
    @XmlAttribute(name = "mass", required = true)
    protected BigDecimal mass;

    /**
     * Open modifications may or may not be localized within a PSM. Additionally, the search pipeline may present multiple possible positions for an open modification, as is the case with MSFragger. List any possible open mod localizations listed by the search pipeline here.Gets the value of the psmOpenModificationPosition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the psmOpenModificationPosition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPsmOpenModificationPosition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PsmOpenModificationPosition }
     * 
     * 
     */
    public List<PsmOpenModificationPosition> getPsmOpenModificationPosition() {
        if (psmOpenModificationPosition == null) {
            psmOpenModificationPosition = new ArrayList<PsmOpenModificationPosition>();
        }
        return this.psmOpenModificationPosition;
    }

    /**
     * Gets the value of the mass property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMass() {
        return mass;
    }

    /**
     * Sets the value of the mass property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMass(BigDecimal value) {
        this.mass = value;
    }

}
